# Generated by Django 5.2.5 on 2025-11-10 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ingredient_scanresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(max_length=14, unique=True)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('last_source', models.CharField(default='ocr', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['gtin', 'created_at'], name='api_scanres_gtin_2375f0_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['gtin'], name='api_item_gtin_d3f1f5_idx'),
        ),
    ]
