# Generated by Django 6.0 on 2026-01-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='custom',
        ),
    ]
